name: "[builder] Build and Push"
# run every two hours to check for updates
on:
  workflow_dispatch:

env:
  TAG: "1.2.0"
  PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
  #PLATFORMS: "linux/amd64,linux/arm64"
  #PLATFORMS: "linux/amd64"

jobs:
  builder-debian-2:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest tags
        run: |
          pwd
          ls -al debian
