
name: [builder] Build and Push

# run every two hours to check for updates
on:
#  schedule:
#  - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push - builder
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.builder
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          #platforms: linux/amd64,linux/arm64
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-builder:1.2.0
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-builder:latest
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-builder:1.2.0
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-builder:latest
