name: "[server, pterodactyl] Auto Build and Push"
# run every two hours to check for updates
on:
#  schedule:
#  - cron: "0 */2 * * *"
  workflow_dispatch:

env:
  #PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
  #PLATFORMS: "linux/amd64,linux/arm64"
  PLATFORMS: "linux/amd64"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest tags
        run: |
          echo "GIT_TAG=$(curl -sL https://api.github.com/repos/tiltedphoques/TiltedEvolution/tags | jq -r '.[].name' | sort -r | head -n 1 | sed 's/v//')" >> $GITHUB_ENV
          echo "GIT_TAG_V=$(curl -sL https://api.github.com/repos/tiltedphoques/TiltedEvolution/tags | jq -r '.[].name' | sort -r | head -n 1)" >> $GITHUB_ENV
          echo "DOCKER_TAG=$(curl -sL https://hub.docker.com/v2/repositories/${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-server/tags | jq -r '.results[].name' | grep -v "latest" | sort -r | head -n 1)" >> $GITHUB_ENV

      - name: Output latest Tags
        run: |
          echo "Git: ${{ env.GIT_TAG }}"
          echo "Git: ${{ env.GIT_TAG_V }}"
          echo "Docker: ${{ env.DOCKER_TAG }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        if: ${{ env.GIT_TAG != env.DOCKER_TAG}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{ env.GIT_TAG != env.DOCKER_TAG}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: ${{ env.GIT_TAG != env.DOCKER_TAG}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ env.GIT_TAG != env.DOCKER_TAG}}
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ env.GIT_TAG != env.DOCKER_TAG}}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push - server
        uses: docker/build-push-action@v6
        if: ${{ env.GIT_TAG != env.DOCKER_TAG}}
        with:
          push: true
          file: Dockerfile.server
          platforms: ${{ env.PLATFORMS }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-server:latest
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:server-latest
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-server:${{ env.GIT_TAG }}
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:server-${{ env.GIT_TAG }}
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-server:latest
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:server-latest
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-server:${{ env.GIT_TAG }}
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:server-${{ env.GIT_TAG }}
          build-args: |
            BRANCH=${{ env.GIT_TAG_V }}

      - name: Build and push - pterodactyl
        uses: docker/build-push-action@v6
        if: ${{ env.GIT_TAG != env.DOCKER_TAG}}
        with:
          push: true
          file: Dockerfile.pterodactyl
          platforms: ${{ env.PLATFORMS }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-pterodactyl:latest
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:pterodactyl-latest
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-pterodactyl:${{ env.GIT_TAG }}
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:pterodactyl-${{ env.GIT_TAG }}
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-pterodactyl:latest
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:pterodactyl-latest
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-pterodactyl:${{ env.GIT_TAG }}
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:pterodactyl-${{ env.GIT_TAG }}
          build-args: |
            BRANCH=${{ env.GIT_TAG }}
